server:
  port: 8084
spring:
  autoconfigure:
    exclude:
  profiles:
    active: qa
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    password:
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 80
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 8